//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House_Rental_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property_Details()
        {
            this.Booking_Details = new HashSet<Booking_Details>();
            this.Property_Images = new List<Property_Images>();
            this.Sold_Property = new HashSet<Sold_Property>();
        }
    
        public int Property_Id { get; set; }
        public string Property_Type { get; set; }
        public string Property_Name { get; set; }
        public string Property_Address { get; set; }
        public string Property_State { get; set; }
        public string Property_City { get; set; }
        public int Property_Pin { get; set; }
        public string Property_Status { get; set; }
        public int Seller_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Details> Booking_Details { get; set; }
        public virtual Seller_Details Seller_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual IList<Property_Images> Property_Images { get; set; }
        public virtual Property_Information Property_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sold_Property> Sold_Property { get; set; }
    }
}
