//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House_Rental_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Information
    {
        public int Property_Id { get; set; }
        public string BHK { get; set; }
        public int Floor { get; set; }
        public int Total_Floor { get; set; }
        public int Age { get; set; }
        public string Facing { get; set; }
        public string Size { get; set; }
        public int ExpectedRent { get; set; }
        public string Expected_Deposit { get; set; }
        public string Preferred_Tenants { get; set; }
        public string Furnishing { get; set; }
        public string Parking { get; set; }
    
        public virtual Property_Details Property_Details { get; set; }
    }
}
